### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by gadelkareem** [jishi/Jishi.StreamToSonos#2]
I wonder if this is compatible with windows 10?

**Comment by jishi** [comment]
Haven't tested it, but unless there are new security restrictions introduced in Win10, it should work. Do note that I haven't looked at this project in a long time, and it is still considered very alpha.

**Comment by gadelkareem** [comment]
It is very useful so far as Sonos did not provide any software that have such functionality. I hope you get the time to improve or rebuild using Electron framework so I could help :).  Thank you!

**Comment by jishi** [comment]
Glad that it is of use. Since it requires access to lower level OS components (audiostream) it is highly unlikely that it would work with a framework like electron though. 

The main issues with the application today is stability and that you have no way of knowing the buffering status of the Sonos players. Because of the way this utilizes the Sonos players, it doesn't really work well when the buffer starts to underrun. Also, since it is a raw PCM stream (16bit, 44kHz uncompressed), it stresses the network quite a bit.

**Comment by gadelkareem** [comment]
Well I do use it a lot to stream sound from laptop while displaying video from project. The only workaround I would think of would be uploading the audio upfront to a steaming service and syncing with the video. That could provide better quality and less stress on the network but the process will be a bit complex.
